# mvn package -Pprod
# docker-compose up --build
# docker-compose down

version: '1'

services:
  demo:
    container_name: jms_demo
    build:
      context: .
      dockerfile: Dockerfile
    image: jms_demo:latest
    networks:
      - some-net
    environment:
      - RABBITMQ_HOST=rabbitmq
networks:
  some-net:
    external:
      name: custom_network