# mvn package -Pprod
# docker-compose up --build
# docker-compose down

version: '1'

services:
  demo:
    container_name: demo
    build:
      context: .
      dockerfile: Dockerfile
    image: demo:latest
    ports:
      - 8080:8080
    depends_on:
      - db

    environment:
      - DB_HOST=localhost
      - DB_PORT=5431
    network_mode: host
  db:
    container_name: db
    image: postgres
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=f57a5ae3756947e8afebe759ebb2b25e
      - POSTGRES_DB=demo
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: