# mvn package -Pprod
# docker-compose up --build
# docker-compose down

version: '1'

services:
  demo:
    container_name: demo
    build:
      context: .
      dockerfile: Dockerfile
    image: demo:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - some-net
    environment:
      - DB_HOST=db
      - DB_PORT=5432
  db:
    container_name: db
    image: postgres
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=f57a5ae3756947e8afebe759ebb2b25e
      - POSTGRES_DB=demo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - some-net
volumes:
  postgres-data:
networks:
  some-net:
    driver: bridge
    name: custom_network